# Generated by Django 4.1.1 on 2023-07-18 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activecamera',
            name='device_status',
            field=models.CharField(default='Unknown', max_length=10),
        ),
    ]
