# Generated by Django 4.1.1 on 2023-07-19 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_alter_activecamera_device_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('description', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ActiveDevices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('CAM', 'Camera'), ('SEN', 'Sensor')], default='CAM', max_length=3)),
                ('name', models.CharField(default='No Name', max_length=100)),
                ('description', models.CharField(default='', max_length=255)),
                ('status', models.CharField(choices=[('ACT', 'Active'), ('INA', 'Inactive'), ('DIS', 'Discovered'), ('UNK', 'Unknown')], default='DIS', max_length=3)),
                ('data', models.JSONField(null=True)),
                ('ip', models.CharField(default='0.0.0.0', max_length=20)),
                ('firmware', models.CharField(default='', max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='devices', to='devices.locations')),
            ],
        ),
    ]
