# Generated by Django 4.1.10 on 2023-07-20 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_locations_activedevices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activedevices',
            name='description',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='activedevices',
            name='status',
            field=models.CharField(choices=[('ACT', 'Active'), ('INA', 'Inactive'), ('DIS', 'Discovered'), ('UNK', 'Unknown'), ('ERR', 'Error')], default='DIS', max_length=3),
        ),
    ]
