# Generated by Django 4.1.10 on 2023-07-28 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0005_alter_activedevices_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ActiveCamera',
        ),
    ]
