# Generated by Django 4.1.10 on 2023-08-01 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlarmConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('type', models.CharField(choices=[('AUD', 'Audible'), ('VIS', 'Visual'), ('BOT', 'Audible and Visual')], default='AUD', max_length=3)),
            ],
        ),
    ]
