# Generated by Django 4.1.10 on 2023-08-01 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alarmconfig',
            name='status',
            field=models.BooleanField(choices=[('ON', 'On'), ('OFF', 'Off')], default='OFF', max_length=3),
        ),
    ]
