# Generated by Django 4.1.10 on 2023-08-01 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarm', '0003_alter_alarmconfig_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='alarmconfig',
            name='current_type',
            field=models.CharField(choices=[('AUD', 'Audible'), ('VIS', 'Visual'), ('BOT', 'Audible and Visual'), ('OFF', 'Off')], default='OFF', max_length=3),
        ),
        migrations.AlterField(
            model_name='alarmconfig',
            name='type',
            field=models.CharField(choices=[('AUD', 'Audible'), ('VIS', 'Visual'), ('BOT', 'Audible and Visual'), ('OFF', 'Off')], default='AUD', max_length=3),
        ),
    ]
