# Generated by Django 4.1.10 on 2023-08-06 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarm', '0004_alarmconfig_current_type_alter_alarmconfig_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetectionObjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_cleaned', models.CharField(default=models.F('name'), max_length=100)),
            ],
        ),
    ]
