# Generated by Django 4.1.10 on 2023-08-06 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarm', '0005_detectionobjects'),
    ]

    operations = [
        migrations.AddField(
            model_name='alarmconfig',
            name='alarm_objects',
            field=models.ManyToManyField(default='all', to='alarm.detectionobjects'),
        ),
    ]
