# Generated by Django 4.1.10 on 2023-08-06 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarm', '0006_alarmconfig_alarm_objects'),
    ]

    operations = [
        migrations.AddField(
            model_name='alarmconfig',
            name='score',
            field=models.DecimalField(decimal_places=3, default=0.5, max_digits=4),
        ),
    ]
