# Generated by Django 4.1.10 on 2023-08-06 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alarm', '0007_alarmconfig_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alarmconfig',
            name='alarm_objects',
        ),
    ]
