# Generated by Django 4.1.10 on 2023-08-15 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarm', '0009_alarmconfig_alarm_objects_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alarmconfig',
            name='alarm_objects',
            field=models.BooleanField(default=False, verbose_name='Alarm on Object Recognition'),
        ),
        migrations.AlterField(
            model_name='alarmconfig',
            name='status',
            field=models.CharField(choices=[('ON', 'On'), ('OFF', 'Off')], default='OFF', max_length=3, verbose_name='Current Alarm Status'),
        ),
        migrations.AlterField(
            model_name='alarmconfig',
            name='type',
            field=models.CharField(choices=[('AUD', 'Audible'), ('VIS', 'Visual'), ('BOT', 'Audible and Visual'), ('OFF', 'Off')], default='AUD', max_length=3, verbose_name='Alarm Type'),
        ),
        migrations.AlterField(
            model_name='detectionobjects',
            name='name_cleaned',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
