# Generated by Django 4.1.10 on 2023-08-15 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('ALA', 'Alarm'), ('CFG', 'Configuration'), ('OTH', 'Other')], default='OTH', max_length=3, verbose_name='Event Type')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(max_length=255)),
                ('source', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
