# Generated by Django 4.1.10 on 2023-08-22 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='type',
            field=models.CharField(choices=[('ALA', 'Alarm'), ('CFG', 'Configuration'), ('CAM', 'Camera'), ('SEN', 'Sensor'), ('IMA', 'Image'), ('TEN', 'TensorFlow'), ('OTH', 'Other')], default='OTH', max_length=3, verbose_name='Event Type'),
        ),
    ]
