# Generated by Django 4.1.1 on 2023-07-12 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imgcapture', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagedetection',
            name='detection_data',
            field=models.TextField(default='{}'),
        ),
    ]
